spring.application.name=finexa

#  Configuração da URL de conexão
spring.datasource.url=jdbc:mysql://localhost:3306/finexa?useSSL=false&serverTimezone=UTC

# Usuário e senha do servidor MySQL
spring.datasource.username=root
spring.datasource.password=root

# Drive de conexão do MySQL
spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver

# Configurações adicionais para o Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
